CREATE TABLE IF NOT EXISTS members (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  full_name VARCHAR(120) GENERATED ALWAYS AS (name) STORED,
  phone VARCHAR(30),
  email VARCHAR(120),
  role VARCHAR(30) NOT NULL DEFAULT 'member',
  joined_on DATE NOT NULL DEFAULT (CURRENT_DATE),
  registration_number VARCHAR(50),
  registration_fee DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  emergency DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  education DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  development DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  fixed_deposit DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  loan_balance DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_members_email (email)
);

CREATE TABLE IF NOT EXISTS savings (
  id INT AUTO_INCREMENT PRIMARY KEY,
  member_id INT NOT NULL,
  amount DECIMAL(12,2) NOT NULL,
  saved_on DATE NOT NULL DEFAULT (CURRENT_DATE),
  notes VARCHAR(255),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_savings_member
    FOREIGN KEY (member_id) REFERENCES members(id)
    ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS loans (
  id INT AUTO_INCREMENT PRIMARY KEY,
  member_id INT NOT NULL,
  amount DECIMAL(12,2) NOT NULL,
  interest_rate DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  issued_on DATE NOT NULL DEFAULT (CURRENT_DATE),
  due_on DATE,
  status VARCHAR(20) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_loans_member
    FOREIGN KEY (member_id) REFERENCES members(id)
    ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS repayments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  loan_id INT NOT NULL,
  member_id INT NOT NULL,
  amount DECIMAL(12,2) NOT NULL,
  paid_on DATE NOT NULL DEFAULT (CURRENT_DATE),
  paid_at DATETIME NULL,
  notes VARCHAR(255),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_repayments_loan
    FOREIGN KEY (loan_id) REFERENCES loans(id)
    ON DELETE CASCADE,
  CONSTRAINT fk_repayments_member
    FOREIGN KEY (member_id) REFERENCES members(id)
    ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS repayment_statements (
  id INT AUTO_INCREMENT PRIMARY KEY,
  member_id INT NOT NULL,
  loan_id INT NOT NULL,
  statement_date DATE NOT NULL DEFAULT (CURRENT_DATE),
  principal_amount DECIMAL(12,2) NOT NULL,
  interest_rate DECIMAL(5,2) NOT NULL,
  total_due DECIMAL(12,2) NOT NULL,
  amount_paid DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  balance_remaining DECIMAL(12,2) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'active',
  generated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_statements_member
    FOREIGN KEY (member_id) REFERENCES members(id)
    ON DELETE CASCADE,
  CONSTRAINT fk_statements_loan
    FOREIGN KEY (loan_id) REFERENCES loans(id)
    ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS uploaded_forms (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  file_name VARCHAR(255) NOT NULL,
  size_label VARCHAR(60) NOT NULL DEFAULT '1 KB',
  data_url LONGTEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS withdrawal_statements (
  id INT AUTO_INCREMENT PRIMARY KEY,
  member_id INT NOT NULL,
  member_name VARCHAR(120) NOT NULL,
  member_reg VARCHAR(50) NOT NULL,
  account VARCHAR(60) NOT NULL,
  account_label VARCHAR(120) NOT NULL,
  amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  balance_before DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  balance_after DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  timestamp DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_withdrawal_statements_member
    FOREIGN KEY (member_id) REFERENCES members(id)
    ON DELETE CASCADE
);
